<?php

namespace App\Enum\Payments;

enum SubscriptionStatusEnum: string
{
    // SUBSCRIPTION ASSIGNED TO USER FROM ADMIN PANEL BUT NOT PAYED YET
    case WAITING = 'WAITING';

    // CURRENT USED SUBSCRIPTION
    case IN_USE = 'IN_USE';

    // SUBSCRIPTION PAYMENT DONE BUT NOT IN USE YET
    case PURCHASED = 'PURCHASED';

    // SUBSCRIPTION IN USE BUT EMPLOYER CONSUME ALL JOB SLOTS
    case CONSUMED = 'CONSUMED';

    // SUBSCRIPTION FINISHED DUE ARRIVAL END TIME
    case FINISHED = 'FINISHED';


}
